create table public.supplier_purchases (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  supplier_id bigint null,
  item_name text null,
  quantity numeric null,
  cost numeric null,
  purchase_date date null,
  notes text null,
  constraint supplier_purchases_pkey primary key (id),
  constraint supplier_purchases_supplier_id_fkey foreign key (supplier_id) references suppliers (id) on delete cascade
);
